---
version: 2
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      args:
        - DOCKER_HOST_IP=${DOCKER_HOST_IP}

    ports:
      - "18080:8080"
#
# Remember!!! Environment only applies to runtime, NOT BUILDTIME for docker, so no --build-args (until docker-compose version 1.9.0.x)
#
    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}

    volumes:
      - /mnt/dockervolumes/data/jenkins:/var/jenkins_home

  nexus:
    build:
      context: ./nexus
      dockerfile: Dockerfile      
    ports:
      - "18081:8081"

    volumes:
      - /mnt/dockervolumes/data/nexus:/sonatype-work

